services:
  app:
    container_name: subscriptions
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    container_name: postgres_db
    image: postgres:15
    environment:
      POSTGRES_USER: lazarenko
      POSTGRES_PASSWORD: lazarenko
      POSTGRES_DB: subscriptions
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./internal/db/migrations:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "lazarenko", "-d", "subscriptions" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  backend:
    driver: bridge