basePath: /
definitions:
  model.Subscription:
    properties:
      end_date:
        example: 12-2025
        type: string
      id:
        example: f4e2c8ad-d773-4d39-85b1-a63d2b2cb41f
        type: string
      price:
        example: 199
        type: integer
      service_name:
        example: Spotify
        type: string
      start_date:
        example: 07-2025
        type: string
      user_id:
        example: 00000000-0000-0000-0000-000000000001
        type: string
    type: object
host: 195.133.20.34:8081
info:
  contact: {}
  description: REST API для управления подписками
  title: Subscriptions API
  version: "1.1"
paths:
  /subscriptions:
    get:
      description: Возвращает все подписки из базы данных
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Subscription'
            type: array
        "500":
          description: Ошибка базы данных
          schema:
            type: string
      summary: Получить список всех подписок
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Создаёт новую подписку для пользователя
      parameters:
      - description: Данные подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/model.Subscription'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Неверный JSON
          schema:
            type: string
        "500":
          description: Ошибка базы данных
          schema:
            type: string
      summary: Создать подписку
      tags:
      - subscriptions
  /subscriptions/{id}:
    delete:
      parameters:
      - description: ID подписки (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Невалидный UUID
          schema:
            type: string
        "404":
          description: Подписка не найдена
          schema:
            type: string
        "500":
          description: Ошибка базы данных
          schema:
            type: string
      summary: Удалить подписку по ID
      tags:
      - subscriptions
    get:
      parameters:
      - description: ID подписки (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Subscription'
        "400":
          description: Неверный UUID
          schema:
            type: string
        "404":
          description: Подписка не найдена
          schema:
            type: string
        "500":
          description: Ошибка базы данных
          schema:
            type: string
      summary: Получить подписку по ID
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      parameters:
      - description: ID подписки (UUID)
        in: path
        name: id
        required: true
        type: string
      - description: Новые данные
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/model.Subscription'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Невалидный UUID или JSON
          schema:
            type: string
        "404":
          description: Подписка не найдена
          schema:
            type: string
        "500":
          description: Ошибка базы данных
          schema:
            type: string
      summary: Обновить подписку по ID
      tags:
      - subscriptions
  /subscriptions/total:
    get:
      parameters:
      - description: UUID пользователя
        in: query
        name: user_id
        type: string
      - description: Название сервиса
        in: query
        name: service_name
        type: string
      - description: Начало периода (MM-YYYY)
        in: query
        name: from
        type: string
      - description: Конец периода (MM-YYYY)
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              format: int64
              type: integer
            type: object
        "400":
          description: Ошибка формата даты или UUID
          schema:
            type: string
        "500":
          description: Ошибка базы данных
          schema:
            type: string
      summary: Получить суммарную стоимость подписок с фильтрацией
      tags:
      - subscriptions
swagger: "2.0"
